#!/usr/bin/env bash

set -e

export BIN="bin/asmjs"
export EXT="html"
export LINK="emcc"
export CFLAGS="--target=asmjs-unknown-emscripten -S "
export DFLAGS="-Iapi/ems -mtriple=asmjs-unknown-emscripten "

make -j`nproc` "DFLAGS=$DFLAGS" "$@"

