#!/usr/bin/env bash

# This script downloads, builds and deploys a D-to-LLVM-to-ASMJS toolchain.
# Usage:
# $ ./fetch_toolchain
# A painfully long time after, you've got a full toolchain in '/tmp/toolchains/'

set -euo pipefail

readonly PREFIX_JS=/tmp/toolchains/llvm-js
readonly PREFIX_EMS=/tmp/toolchains/emscripten
readonly tmpDir=/tmp/emsd-source
readonly scriptDir=$(realpath $(dirname $0))

function main
{
  mkdir -p $tmpDir

  buildEmscripten
  buildLdc

  configureEmcc

  PATH="$PREFIX_EMS:$PATH" \
    buildExtraLibs

  echo "Success. Your asmjs toolchain is now ready."
}

function configureEmcc
{
  # will create $HOME/.emscripten
  PATH=$PREFIX_JS/bin:$PATH \
    $PREFIX_EMS/emcc --version
}

function buildExtraLibs
{
  buildSdl2Mixer
}

function buildSdl2Mixer
{
  mkdir -p $tmpDir/SDL2_mixer

  wget https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.1.tar.gz -O $tmpDir/SDL2_mixer.tar.gz
  runFrom $tmpDir tar xzf $tmpDir/SDL2_mixer.tar.gz
  rm -rf $tmpDir/SDL2_mixer
  mv $tmpDir/SDL2_mixer-2.0.1 $tmpDir/SDL2_mixer

  mkdir -p $tmpDir/bin/SDL2_mixer
  runFrom $tmpDir/bin/SDL2_mixer emconfigure ../../SDL2_mixer/configure \
    CFLAGS="-O3 -s USE_OGG=1 -s USE_VORBIS=1" \
    --prefix="$PREFIX_EMS/system" \
    --disable-sdltest \
    --enable-shared \
    --enable-music-ogg \
    --disable-music-mp3 \
    --disable-music-flac \
    --disable-music-midi \
    --disable-music-mod
  runFrom $tmpDir/bin/SDL2_mixer emmake make -j`nproc` install
}

# Here, we build and install:
# - vanilla LLVM (3.9)
# - ldc D2 compiler (requires LLVM >= 3.5)
function buildLdc
{
  if [ ! -d $tmpDir/ldc ] ; then
    git clone -b master --single-branch --recursive https://github.com/ldc-developers/ldc.git $tmpDir/ldc
    gitCheckout $tmpDir/ldc 'a89719d7bd88b5f97aed06098c44b80402e61dd9'
    patch -d $tmpDir/ldc -p1 -i $scriptDir/ldc.patch
  fi

  mkdir -p $tmpDir/bin/ldc
  runFrom $tmpDir/bin/ldc cmake \
    -G "Unix Makefiles" \
    -D "CMAKE_INSTALL_PREFIX=$PREFIX_JS" \
    -D "LLVM_CONFIG=$PREFIX_JS/bin/llvm-config" \
    ../../ldc
  runFrom $tmpDir/bin/ldc make -j`nproc`
  runFrom $tmpDir/bin/ldc make -j`nproc` install
}

# Here, we build and install:
# - 'fastcomp' LLVM
# - 'fastcomp' clang frontend (which requires 'fastcomp' LLVM)
# - emscripten (python wrapper scripts + header files + pkg-config files)
function buildEmscripten
{
  # emcc and other python wrappers
  if [ ! -d $PREFIX_EMS ] ; then
    git clone --depth=1 -b master --single-branch https://github.com/kripken/emscripten.git $PREFIX_EMS
    #gitCheckout $PREFIX_EMS '07b87426f898d6e9c677db291d9088c839197291'

    # fake pkg-config files to keep happy the build systems of user projects, which don't know about emscripten
    cp $PREFIX_EMS/system/lib/pkgconfig/sdl.pc $PREFIX_EMS/system/lib/pkgconfig/SDL_mixer.pc
    cp $PREFIX_EMS/system/lib/pkgconfig/sdl.pc $PREFIX_EMS/system/lib/pkgconfig/SDL_image.pc
    cp $PREFIX_EMS/system/lib/pkgconfig/sdl.pc $PREFIX_EMS/system/lib/pkgconfig/SDL_gfx.pc

    generateGlPc > $PREFIX_EMS/system/lib/pkgconfig/gl.pc
    generateSdl2Pc > $PREFIX_EMS/system/lib/pkgconfig/sdl2.pc
    generateSdl2ImagePc > $PREFIX_EMS/system/lib/pkgconfig/SDL2_image.pc
    cp $PREFIX_EMS/system/lib/pkgconfig/sdl2.pc $PREFIX_EMS/system/lib/pkgconfig/SDL2_mixer.pc
  fi

  # the asmjs backend
  if [ ! -d $tmpDir/emscripten-llvm ] ; then
    git clone --depth=1 -b master --single-branch https://github.com/kripken/emscripten-fastcomp.git $tmpDir/emscripten-llvm
    gitCheckout $tmpDir/emscripten-llvm '881bd352731d21c7117ad7e2ece347aacae83965'
  fi

  # modified clang front-end (why the hell is it even necessary to modify the frontend?)
  if [ ! -d $tmpDir/emscripten-llvm/tools/clang ] ; then
    git clone --depth=1 -b master --single-branch https://github.com/kripken/emscripten-fastcomp-clang.git $tmpDir/emscripten-llvm/tools/clang
    gitCheckout $tmpDir/emscripten-llvm/tools/clang '60a7e9a9c22b67309e5b1258d38fadfa481a25d3'
  fi

  mkdir -p $tmpDir/bin/emscripten-llvm

  runFrom $tmpDir/bin/emscripten-llvm cmake \
    -G "Unix Makefiles" \
    -D "CMAKE_INSTALL_PREFIX=$PREFIX_JS" \
    -D "CMAKE_BUILD_TYPE=Release" \
    -D "LLVM_BUILD_GLOBAL_ISEL=off" \
    -D "LLVM_TARGETS_TO_BUILD=host;JSBackend" \
    -D "LLVM_ENABLE_ASSERTIONS=off" \
    -D "LLVM_ENABLE_BACKTRACES=off" \
    -D "LLVM_ENABLE_WARNINGS=off" \
    -D "CLANG_ENABLE_STATIC_ANALYZER=off" \
    -D "CLANG_ENABLE_ARCMT=off" \
    ../../emscripten-llvm

  runFrom $tmpDir/bin/emscripten-llvm make -j`nproc`
  runFrom $tmpDir/bin/emscripten-llvm make -j`nproc` install
}

function generateGlPc
{
  echo "Name: gl"
  echo "Description: gl"
  echo "Version: 2.0.0"
  echo "Cflags: "
  echo "Libs: -lGL"
}

function generateSdl2Pc
{
  echo "Name: sdl2"
  echo "Description: SDL2"
  echo "Version: 2.0.0"
  echo "Cflags: -s USE_SDL=2"
  echo "Libs: -s USE_SDL=2"
}

function generateSdl2ImagePc
{
  echo "Name: SDL2_image"
  echo "Description: SDL2_image"
  echo "Version: 2.0.0"
  echo "Cflags: -s USE_SDL_IMAGE=2"
  echo "Libs: -s USE_SDL_IMAGE=2"
}

function gitCheckout
{
  local dir=$1
  local commit=$2

  runFrom $dir git fetch --depth 100
  runFrom $dir git checkout "$commit"
}

function runFrom
{
  local readonly dir=$1
  shift
  pushd $dir >/dev/null
  "$@"
  popd >/dev/null
}

main "$@"

